---
title: "R Notebook"
output: html_notebook
---

```{r}
project <<- "mc_tm"
task.id <<- 8
source("../scripts/readers.R")
source("../scripts/mc_functions.R")
source("../scripts/fc_plots.R")
source("../scripts/settings.R")
source("../scripts/local_settings.R")
```

```{r}
subcluster <- function(target.cl, n.pieces, tsne.perplexity, min.pval) {
  tasks.per.res <- tasks.per.tiss #how many different methods per one resolution
  res <<- 1
  method <<- switch(task.id %% tasks.per.res + 1, "none", "z_score", "cutoff", "outlier", "mad") #filtering method
  param <<- switch(task.id %% tasks.per.res + 1, 0, 2, 10, 0, 2) #filtering parameter
  
  source.dir <<- paste0(source.dir.prefix, project, "/", tissue, "/", res, "-", method, "-", param, "/")

  task.name <<- paste(tissue, res, method, param, target.cl, sep = "-")
  results.dir <<- paste0(output.dir, "plots/", task.name, "/")
  dir.create(paste0(output.dir, "plots/"), showWarnings = FALSE)
  dir.create(results.dir, showWarnings = FALSE)
  
  cells <- read.csv(paste0(source.dir, "!cells.csv"))
  clusters <- read.csv(paste0(source.dir, "!clusters.csv"))  
  
  all.cells <- colnames(tiss$RNA)
  retained <- cells$X
  pass <- list()
  pass[all.cells] <- FALSE
  pass[intersect(all.cells, retained)] <- TRUE
  tiss[["pass"]] <- factor(as.character(pass))
  
  tiss <<- tiss[,pass == TRUE]

  clst <- cells$cluster
  names(clst) <- cells$cell
  tiss$old_clusters <<- cells$cluster
  annotations <- clusters$annotation
  cell.types <- clusters$cell.type
  
  cluster.obj <<- subset(tiss, old_clusters == target.cl)
  
  tmp <- clusterize(cluster.obj, res, compute.reductions = TRUE, compute.markers = TRUE, n.pieces = n.pieces, tsne.perplexity = tsne.perplexity) #cluster cells
  #unpack returned object
  cluster.obj <<- tmp$obj
  obj.markers <<- tmp$markers
  
  tmp <- assignCellTypes(cluster.obj, obj.markers, getAnnotations(cluster.obj), record.stats = TRUE, min.pval = min.pval) #assign cell types
  #unpack returned object
  clusters <<- tmp$clusters
  obj.markers <<- tmp$markers
  
  generatePlots(cluster.obj, task.name, clusters$cell.type, clusters$annotation, sig.plots = FALSE) #make plots
  generateMarkerPlots(cluster.obj, obj.markers %>% group_by(cluster) %>% top_n(n = 9, wt = avg_logFC))
  
  saveResults(cluster.obj, clusters, obj.markers, mc_specific=FALSE)
  
  print(cell.types[target.cl])
}
```


```{r}
tiss <- AutoReader(project, cells.filter, features.filter, tasks.per.tiss)
bkp <- tiss
```


```{r}
tiss <- bkp
target.cl <- 5
too.little.cells <- TRUE
if (too.little.cells) {
  subcluster(target.cl, n.pieces=10, tsne.perplexity=10, min.pval=1.01)
} else {
  subcluster(target.cl, n.pieces=50, tsne.perplexity=30, min.pval=0.05)
}
```

