---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(Seurat)
library(ggplot2)
library(gridExtra)
```

```{r}
minr <- function(x) {
  return(round(min(x), digits = 2))
}

maxr <- function(x) {
  return(round(max(x), digits = 2))
}

meanr <- function(x) {
  return(round(mean(x), digits = 2))
}

medianr <- function(x) {
  return(round(median(x), digits = 2))
}
```

```{r}
tiss <- NULL
tissue <- "HCA_immune"
path <- paste0("~/Downloads/", tissue)

line <- tissue
cells <- 0
features <- 0
tiss <- CreateSeuratObject(counts = Read10X(data.dir =  path), min.cells = cells, min.features = features)
#tiss <- CreateSeuratObject(counts = read.table(file = paste0(path, ".csv", header = TRUE,), min.cells = cells, min.features = features))

tiss[["percent.mt"]] <- PercentageFeatureSet(object = tiss, features=grep("^MT-", rownames(tiss$RNA), ignore.case=TRUE))
tiss[["percent.rb"]] <- PercentageFeatureSet(object = tiss, features=grep("^(RPL)|(RPS)", rownames(tiss$RNA), ignore.case=TRUE))
line <- paste(line, minr(tiss$nCount_RNA), meanr(tiss$nCount_RNA), median(tiss$nCount_RNA), 
              minr(tiss$nFeature_RNA), meanr(tiss$nFeature_RNA), medianr(tiss$nFeature_RNA), 
              maxr(tiss$percent.mt), meanr(tiss$percent.mt), medianr(tiss$percent.mt), 
              maxr(tiss$percent.rb), meanr(tiss$percent.rb), medianr(tiss$percent.rb), sep=",")
write(line, file="output.csv", append=TRUE)

```
```{r}
VlnPlot(object = tiss, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), group.by="orig.ident", ncol = 4)
```




